### PR TITLE
Alistair

### PR DESCRIPTION
**Pull request by ab604**
Hi,

This PR should be for my Rmarkdown file based upon your original one. As usual I get confused once it comes to merging so I'm not sure what is going to happen!

I've not achieved a great deal here beyond re-plotting the first part of your analysis and hopefully clarifying a few things. Most of my time has been spent trying to make sense of the TEF documentation. I've reworked things tidyverse style.

All the best,

Alistair

### CODE REVIEW

**Comment by oscci** [comment]
Many thanks. I have to focus on the day job now but aim to take a look on Weds.

On 17 Feb 2019, at 20:05, Alistair Bailey <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

This PR should be for my Rmarkdown file based upon your original one. As usual I get confused once it comes to merging so I'm not sure what is going to happen!

I've not achieved a great deal here beyond re-plotting the first part of your analysis and hopefully clarifying a few things. Most of my time has been spent trying to make sense of the TEF documentation. I've reworked things tidyverse style.

All the best,

Alistair

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/oscci/TEF2019/pull/1

Commit Summary

  *   initial commit
  *   initial commit
  *   Add Rmd

File Changes

  *   A .gitignore<https://github.com/oscci/TEF2019/pull/1/files#diff-0> (7)
  *   A TEF2019.Rproj<https://github.com/oscci/TEF2019/pull/1/files#diff-1> (13)
  *   A TEF4-analyse-AB-17-02-2019.Rmd<https://github.com/oscci/TEF2019/pull/1/files#diff-2> (219)
  *   A TEF4-analyse-AB-17-02-2019.html<https://github.com/oscci/TEF2019/pull/1/files#diff-3> (763)
  *   A TEF4-analyse-AB-17-02-2019_cache/html/__packages<https://github.com/oscci/TEF2019/pull/1/files#diff-4> (18)
  *   A TEF4-analyse-AB-17-02-2019_cache/html/read_explore_data_c77abafcec771e33250327ca7dbb96b8.RData<https://github.com/oscci/TEF2019/pull/1/files#diff-5> (0)
  *   A TEF4-analyse-AB-17-02-2019_cache/html/read_explore_data_c77abafcec771e33250327ca7dbb96b8.rdb<https://github.com/oscci/TEF2019/pull/1/files#diff-6> (0)
  *   A TEF4-analyse-AB-17-02-2019_cache/html/read_explore_data_c77abafcec771e33250327ca7dbb96b8.rdx<https://github.com/oscci/TEF2019/pull/1/files#diff-7> (0)
  *   A TEF4-analyse-AB-17-02-2019_files/figure-html/explore-1.png<https://github.com/oscci/TEF2019/pull/1/files#diff-8> (0)
  *   A TEF4-analyse-AB-17-02-2019_files/figure-html/selectcore-1.png<https://github.com/oscci/TEF2019/pull/1/files#diff-9> (0)

Patch Links:

  *   https://github.com/oscci/TEF2019/pull/1.patch
  *   https://github.com/oscci/TEF2019/pull/1.diff

**Comment by ab604** [comment]
Great. I’ll also carry on when time permits. I foolishly thought this would be a fun alternative to doing a Tidy Tuesday!

**Review by oscci — APPROVED** [review]

**Comment by oscci** [comment]
Many thanks - am merging these and will study and learn from them!

**Comment by oscci** [comment]
Next week I plan to do a major update - am now including data from previous years - feel free to continue to work on this one, but it may be better to wait until I have a newer and more streamlined script.

**Comment by oscci** [comment]
Hi Alistair

Just to say that I was confused that when I accepted the pull request, nothing changed!
I've worked out that this is because you changed the name of the file.
In many ways this is good, because I am changing things massively anyhow, and this way I can import the bits of what you have done that I need.

I'm quite a newbie to github, but I think the general idea is that you keep the original filename, so that then the originator can pull in your changes if they like them and doesn't have to cut and paste.And you can always retrieve the original version, so there is no danger of damaging it.

Anyhow, many thanks for all your efforts. I am stumbling along learning about Github and it is v good to have your input.
It is a nightmare dataset. If it is any consolation, the 2017 data is far worse because they used letters as missing data codes within numerical columns!

Dorothy

On 18 Feb 2019, at 19:23, Alistair Bailey <notifications@github.com<mailto:notifications@github.com>> wrote:

Great. I’ll also carry on when time permits. I foolishly thought this would be a fun alternative to doing a Tidy Tuesday!

**Comment by ab604** [comment]
Hi Dorothy,

Yes I’m a novice with pull requests and merges. In this instance I thought it better to create a new file as I’d deleted so much of your original document, but I take your point about the purpose of version control.

The only other thing I’ve done since is to scale the size of the points on the plots according to the difference as the flags measure two things, material difference from benchmark (whatever that is!  😊) and the z-score significance. I also drop all the “Not significant” flags in this code for clarity. It doesn’t add a great deal, but reinforces the idea the larger institutions do significantly better or worse that smaller ones in general.

```
tidy_tef %>% 
        filter(split_id =='Core',denominator > 0 & denominator <= 15000, modeofstudy =='FullTime', !is.na(flagn) & flagn != "Not significant") %>% #View()
        ggplot(aes(denominator,zscore)) +
        geom_point(aes(colour = flagn, size  = difference),alpha = 0.5) + 
        scale_x_continuous(trans = "log10") +
        scale_color_discrete() +
        xlab("Log N students") +
        ylab("z-score") +
        facet_wrap(~metric) +
        theme(text = element_text(size = 8),
              `legend.position="top")

```
I plotted difference vs z-score, with the points scaled to N students too, which is another way of seeing the same thing:

```
tidy_tef` %>% 
        filter(split_id =='Core',denominator > 0 & denominator <= 15000, modeofstudy =='FullTime', !is.na(flagn) & flagn != "Not significant") %>% #View()
        ggplot(aes(difference,zscore)) +
        geom_point(aes(colour = flagn, size  = denominator),alpha = 0.3) + 
        #scale_x_continuous(trans = "log10") +
        ylab("Z-score") +
        xlab("Material difference from benchmark") +
        facet_wrap(~metric) +
        theme(text = element_text(size = 8),
              legend.position="top") +
              #legend.title = element_blank()) +
        guides(colour = guide_legend("Flag"), size = guide_legend("N `students"))

```
Just under two thirds of the flags are ‘Not significant’, but this ranges from 46% to 79% by metric. Change the commented lines here if you want the values by metric:

```
tidy_tef` %>% 
        filter(split_id =='Core',denominator > 0, 
               modeofstudy =='FullTime', 
               !is.na(flagn)) %>% 
        group_by(metric,flagn) %>% 
        #group_by(flagn) %>% 
        summarise (n = n()) %>%
        mutate(freq = n / sum(n)) #%>% 
        #filter(metric == `"HighlySkilledEmploymentOrFurtherStudy")
```

I won’t do any more until you publish your next update. Hope that’s useful in the meantime.

All the best,

Alistair

**Comment by oscci** [comment]
Just to say this is v useful. I really want to move to using tidyverse now, and these examples are great in showing me how to do various operations.
I have some time next week to play further.

On 21 Feb 2019, at 17:20, Alistair Bailey <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dorothy,

Yes I’m a novice with pull requests and merges. In this instance I thought it better to create a new file as I’d deleted so much of your original document, but I take your point about the purpose of version control.

The only other thing I’ve done since is to scale the size of the points on the plots according to the difference as the flags measure two things, material difference from benchmark (whatever that is! 😊) and the z-score significance. I also drop all the “Not significant” flags in this code for clarity. It doesn’t add a great deal, but reinforces the idea the larger institutions do significantly better or worse that smaller ones in general.

tidy_tef %>% filter(split_id =='Core',denominator > 0 & denominator <= 15000, modeofstudy =='FullTime', !is.na(flagn) & flagn != "Not significant") %>% #View() ggplot(aes(denominator,zscore)) + geom_point(aes(colour = flagn, size = difference),alpha = 0.5) + scale_x_continuous(trans = "log10") + scale_color_discrete() + xlab("Log N students") + ylab("z-score") + facet_wrap(~metric) + theme(text = element_text(size = 8), legend.position="top")`

I plotted difference vs z-score, with the points scaled to N students too, which is another way of seeing the same thing:

tidy_tef %>%
filter(split_id =='Core',denominator > 0 & denominator <= 15000, modeofstudy =='FullTime', !is.na(flagn) & flagn != "Not significant") %>% #View()
ggplot(aes(difference,zscore)) +
geom_point(aes(colour = flagn, size = denominator),alpha = 0.3) +
#scale_x_continuous(trans = "log10") +
ylab("Z-score") +
xlab("Material difference from benchmark") +
facet_wrap(~metric) +
theme(text = element_text(size = 8),
legend.position="top") +
#legend.title = element_blank()) +
guides(colour = guide_legend("Flag"), size = guide_legend("N students"))

Just under two thirds of the flags are ‘Not significant’, but this ranges from 46% to 79% by metric. Change the commented lines here if you want the values by metric:

tidy_tef %>%
filter(split_id =='Core',denominator > 0,
modeofstudy =='FullTime',
!is.na(flagn)) %>%
group_by(metric,flagn) %>%
#group_by(flagn) %>%
summarise (n = n()) %>%
mutate(freq = n / sum(n)) #%>%
#filter(metric == "HighlySkilledEmploymentOrFurtherStudy")

I won’t do any more until you publish your next update. Hope that’s useful in the meantime.

All the best,

Alistair

**Comment by ab604** [comment]
You’re most welcome. I always enjoy reading your blogs and tweets, so it’s nice to give something back.

If you’re not already a member of Rstudio Community, I highly recommend it. Very friendly and rapid responses: https://community.rstudio.com/

I have some tidyverse materials I put together for a workshop here: https://ab604.github.io/docs/bspr_workshop_2018/tidyverse.html and https://ab604.github.io/docs/bspr_workshop_2018/dplyr.html

But of course the best tidyverse primer is Hadley Wickham’s book: https://r4ds.had.co.nz/

**Comment by oscci** [comment]
Dear Alistair

I've got a bit sidetracked!
I think I've found an algebraic error in the TEF benchmarking formula.
This is huge if true. I've spent a lot of time checking this out with simulated data.

I'm creating a Rmd document focusing specifically on trying to explain this.
I will incorporate some of your code and acknowledge your help, but I've done far less with tidyverse than I had hoped. The bits I have incorporated from you are super-useful anyhow, but I keep reverting to clunky old code just to get things done. I'm sure you know how that is.
Ideally I want to work through cleaning up the code and teaching myself more tidyverse, but my top priority now is just getting this analysis out in the public domain.

I'll push this to github when I've done some more.

thanks again for your help

Dorothy



On 22 Feb 2019, at 15:36, Alistair Bailey <notifications@github.com<mailto:notifications@github.com>> wrote:

You’re most welcome. I always enjoy reading your blogs and tweets, so it’s nice to give something back.

If you’re not already a member of Rstudio Community, I highly recommend it. Very friendly and rapid responses: https://community.rstudio.com/

I have some tidyverse materials I put together for a workshop here: https://ab604.github.io/docs/bspr_workshop_2018/tidyverse.html and https://ab604.github.io/docs/bspr_workshop_2018/dplyr.html

But of course the best tidyverse primer is Hadley Wickham’s book: https://r4ds.had.co.nz/

**Comment by ab604** [comment]
Hi Dorothy,

No problem, I did see the tweets from yourself and Hetan Shah about the benchmark.

I had actually been intending to email you about the flags, as last weekend I decided to check their working and I spent about an hour not being able to reproduce their numbers and thought it was my code! Having seen the comments about the benchmark, I’m now wondering whether it’s not just the benchmark that is incorrect – although if it the benchmark is wrong, then the it makes the flag calculation redundant. But it certainly doesn’t give me a great deal of confidence in the rest of the TEF calculations. In the case of the flags, I still suspect my code is not quite right, but they have several caveats for each flag, so the whole thing is quite messy anyway.

I don’t know if you follow those guys already, but if you do want to get into tidyverse a bit more in the future then (and there are lots of other great useRs too):

+ David Robinson https://twitter.com/drob  live casts his attempts at Tidy Tuesday so you can see how he tackles a data set he’s never seen. This is his latest: https://www.youtube.com/watch?v=bmaigtpKyiM

+ And I think Nick Tierny https://twitter.com/nj_tierney has started a just-three-things live cast initiative for short tips.

+ Mara Averick is a non-stop supply of tidyverse information: https://twitter.com/dataandme

As for using clunky old code, I’m sure there’s some pithy Hadley Wickham comment I came across when I was doing one of his DataCamp courses about getting it working being more important than making it elegant, and that’s the difference between at the practitioner end of the spectrum rather than the programmer end – in fact I made a slide about it a few months ago: https://ab604.github.io/docs/umea-swc-slides-12-10-2018.html#4


I’ll take a look when you push the next version, and also have a look at the flags again tomorrow.

All the best,

Alistair

**Comment by oscci** [comment]
Many thanks for all your help - it's been v. useful .
Because I want to see how different z-scores impact on TEF awards, I've gone to the 2017 data, where the award is listed with the other raw data.

I agree that the flags seem a bit cryptic.

I've just pushed a long and complicated rmd file - basically this does the following:

a. Provides functions that replicate Draper-Gittoes method for benchmarking, including computation of standard errors.
b. Show that this gives far too many extreme z-scores (this was already noted by Draper and Gittoes)
c. Show that there are too many extreme z-scores in the real TEF data too.
d. Show that changing the formula for computing SEs gives a more realistic looking set of z-scores (though I can't be sure this is valid - it's very much suck it and see).
e. Suggest that use of quantile cutoffs makes more sense than cutoff of zscore 2 and 3
f. Show how this would have affects gold/silver/bronze awards in year 2. - basically far fewer institutions would have qualified for these.

A weird thing is that some of those who got bronze seemed to get positive scores on flag.
But I have got too tired to double check this and will come back to check this when fresher.

All best

Dorothy



On 2 Mar 2019, at 12:30, Alistair Bailey <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Dorothy,

No problem, I did see the tweets from yourself and Hetan Shah about the benchmark.

I had actually been intending to email you about the flags, as last weekend I decided to check their working and I spent about an hour not being able to reproduce their numbers and thought it was my code! Having seen the comments about the benchmark, I’m now wondering whether it’s not just the benchmark that is incorrect – although if it the benchmark is wrong, then the it makes the flag calculation redundant. But it certainly doesn’t give me a great deal of confidence in the rest of the TEF calculations. In the case of the flags, I still suspect my code is not quite right, but they have several caveats for each flag, so the whole thing is quite messy anyway.

I don’t know if you follow those guys already, but if you do want to get into tidyverse a bit more in the future then (and there are lots of other great useRs too):

+ David Robinson https://twitter.com/drob live casts his attempts at Tidy Tuesday so you can see how he tackles a data set he’s never seen. This is his latest: https://www.youtube.com/watch?v=bmaigtpKyiM

+ And I think Nick Tierny https://twitter.com/nj_tierney has started a just-three-things live cast initiative for short tips.

+ Mara Averick is a non-stop supply of tidyverse information: https://twitter.com/dataandme

As for using clunky old code, I’m sure there’s some pithy Hadley Wickham comment I came across when I was doing one of his DataCamp courses about getting it working being more important than making it elegant, and that’s the difference between at the practitioner end of the spectrum rather than the programmer end – in fact I made a slide about it a few months ago: https://ab604.github.io/docs/umea-swc-slides-12-10-2018.html#4


I’ll take a look when you push the next version, and also have a look at the flags again tomorrow.

All the best,

Alistair

**Comment by ab604** [comment]
Hi Dorothy,

I've finally had a chance to start looking at this again, but have only skimmed through it due to time limitations. Two minor comments, that you may or may not be aware of already, apologies if you are:

1. If you set a seed for your random number generator at the top of your file with `set.seed()` your simulations will be reproducible, [http://rfunction.com/archives/62](http://rfunction.com/archives/62) 

2. The documentation for the flags I read stated that the difference between indicator and benchmark can be ignored if the benchmark was greater than 97, which I take to mean only z-score matters under those circumstances. From p.42-43 [Technical Specifications](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/658490/Teaching_Excellence_and_Student_Outcomes_Framework_Specification.pdf) 

Not sure if that effects anything in your blog, but I found 15 institutions who's awards appear to be based on z-score alone (this is the year 4 data):

`tef4file %>% 
filter(benchmark > 97, split_id =='Core',denominator > 0, modeofstudy =='FullTime') %>% 
View()`

I'll try and read your code more thoroughly later. All the best,

Alistair

**Comment by oscci** [comment]
many thanks.
I've got a couple of statistics uber-experts also interested, and everyone agrees it is a bit of a train-wreck.
With help from others, I did a new script specifically on benchmarking, as a lot of my original script was redundant once I worked out how the z-scores were computed (ie with SE rather than SD as denominator).

It would be particularly interesting to see which institutions would get bronze under TEF rules, but have normal range z-scores when computed in a conventional fashion: I think they would be v interested to know! I have been planning to look at that but I have a very busy March with a lot of travelling so it's not happened.

To be honest, I am also wondering if it's worth putting a lot more time into this. I am very pleased to see strong critiques of TEF from Royal Statistical Society, UUK and Russell Group.
It's hard to see how subject-level TEF could survive after that, and I live in hopes that TEF might be ditched altogether: the institutional-level TEF really seems like a slegehammer to crack a nut and it's not sure the resulting awards are of any use to anyone.
However, I guess dropping TEF altogether would be embarrassing for dFE and OfS so perhaps it will live on in some form.

D

On 10 Mar 2019, at 08:50, Alistair Bailey <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dorothy,

I've finally had a chance to start looking at this again, but have only skimmed through it due to time limitations. Two minor comments, that you may or may not be aware of already, apologies if you are:

  1.  If you set a seed for your random number generator at the top of your file with set.seed() your simulations will be reproducible, http://rfunction.com/archives/62

  2.  The documentation for the flags I read stated that the difference between indicator and benchmark can be ignored if the benchmark was greater than 97, which I take to mean only z-score matters under those circumstances. From p.42-43 Technical Specifications<https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/658490/Teaching_Excellence_and_Student_Outcomes_Framework_Specification.pdf>

Not sure if that effects anything in your blog, but I found 15 institutions who's awards appear to be based on z-score alone (this is the year 4 data):

tef4file %>% filter(benchmark > 97, split_id =='Core',denominator > 0, modeofstudy =='FullTime') %>% View()

I'll try and read your code more thoroughly later. All the best,

Alistair

**Comment by ab604** [comment]
Thanks Dorothy.  Yes, I think it’s time for me to defer to the stats experts, and likewise deadlines are looming for my official work. But I do find it an excellent learning experience to dig through code and documentation and see how other people approach/solve these things. Annoying as the TEF dataset may be.

My only expectation for people abandoning poorly designed metrics is that it saves them money to do so.

Alistair

**Pull request closed without merging**
